name: build-windows-exe-debug

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repository tree (top level)
        shell: powershell
        run: |
          Get-ChildItem -Force
          Write-Host "----"
          Get-ChildItem -Force Interface, Csv, Parsers, DataAnalytics, Lexicons, Urls, drivers -Recurse -ErrorAction SilentlyContinue

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.6'   # поставь свою версию

      - name: pip bootstrap
        shell: powershell
        run: |
          python -V
          python -m pip install --upgrade pip setuptools wheel
          if (Test-Path requirements.txt) {
            pip install -r requirements.txt
          }
          # На всякий случай: то, что PyInstaller любит
          pip install pyinstaller pyqt6 matplotlib pywin32-ctypes packaging

      - name: Freeze list
        shell: powershell
        run: pip freeze

      - name: Build GUI (DEBUG log)
        shell: powershell
        run: |
          if (-Not (Test-Path "Interface\interface.py")) {
            Write-Error "Interface\interface.py not found"
          }
          pyinstaller Interface/interface.py `
            --noconfirm `
            --onefile `
            --windowed `
            --name ReviewAnalytics `
            --log-level DEBUG `
            --collect-submodules PyQt6 `
            --collect-data PyQt6 `
            --collect-data matplotlib `
            --hidden-import PyQt6.QtCore `
            --hidden-import PyQt6.QtGui `
            --hidden-import PyQt6.QtWidgets `
            --add-data "Csv;Csv" `
            --add-data "Lexicons;Lexicons" `
            --add-data "Urls;Urls" `
            --add-data "DataAnalytics;DataAnalytics" `
            --add-data "drivers;drivers" `
            --add-binary "drivers\*.exe;drivers" `
            --add-binary "drivers\*.dll;drivers"

      - name: Upload GUI artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ReviewAnalytics-GUI-debug
          path: |
            dist/ReviewAnalytics.exe
            build/ReviewAnalytics/*
            *.spec
